listen ${NGINX_HTTP_PORT} default_server;
listen [::]:${NGINX_HTTP_PORT} default_server;

server_name _;
root ${NGINX_WEBROOT};
index index.php;
charset utf-8;
absolute_redirect off;

location = /healthcheck {
    access_log off;
    fastcgi_read_timeout 5s;
    include fastcgi_params;
    fastcgi_param SCRIPT_NAME /healthcheck;
    fastcgi_param SCRIPT_FILENAME /healthcheck;
    fastcgi_pass 127.0.0.1:9000;
}

location / {
    try_files $uri $uri/ /index.php?$query_string;
}

location ^~ /build/ {
    try_files $uri =404;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
}

location ^~ /storage/ {
    alias /var/www/html/storage/app/public/;
    try_files $uri =404;
}

error_page 404 /index.php;

location ~ ^/index\.php(/|$) {
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_param HTTP_HOST $http_host;
    fastcgi_param SERVER_NAME $host;
    fastcgi_param REQUEST_SCHEME $scheme;
    fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
    fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
    fastcgi_param HTTP_X_FORWARDED_PORT $http_x_forwarded_port;
    fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
    fastcgi_param HTTPS $https if_not_empty;
    include fastcgi_params;
    fastcgi_buffers ${NGINX_FASTCGI_BUFFERS};
    fastcgi_buffer_size ${NGINX_FASTCGI_BUFFER_SIZE};
    fastcgi_read_timeout ${PHP_MAX_EXECUTION_TIME};
    fastcgi_hide_header X-Powered-By;
    internal;
}

location ~ \.php$ {
    return 404;
}

include /etc/nginx/server-opts.d/*.conf;
